project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Hands On Exercises"
        menu:
          - text: "Week 1"
            href: "Hands-On-Exercises/chapter-02/HOE1.qmd"
          - text: "Week 2"
            href: "Hands-On-Exercises/chapter-03/HOE2.qmd"
          - text: "Week 3"
            href: "Hands-On-Exercises/chapter-04/HOE3.qmd"
          - text: "Week 6"
            href: "Hands-On-Exercises/chapter-08/HOE6.qmd"
          - text: "Week 7"
            href: "Hands-On-Exercises/chapter-09/HOE7.qmd"
          - text: "Week 9"
            href: "Hands-On-Exercises/chapter-13/HOE8.qmd"
      - text: "In Class Exercises"
        menu: 
          - text: "Week 2"
            href: "In-Class-Exercises/chapter-02/ICE2.qmd"
          - text: "Week 3"
            href: "In-Class-Exercises/chapter-03/ICE3.qmd"
          - text: "Week 4"
            href: "In-Class-Exercises/chapter-04/ICE4.qmd"
          - text: "Week 5"
            href: "In-Class-Exercises/chapter-05/ICE5.qmd"
          - text: "Week 6"
            href: "In-Class-Exercises/chapter-06/ICE6.qmd"
          - text: "Week 7"
            href: "In-Class-Exercises/chapter-07/ICE7.qmd"
          - text: "Week 9"
            href: "Hands-On-Exercises/chapter-13/HOE8.qmd"
          - text: "Week 10"
            href: "In-Class-Exercises/chapter-12/ICE9.qmd"
          - text: "Week 11"
            href: "In-Class-Exercises/chapter-16/ICE10.qmd"
          - text: "Week 12"
            href: "In-Class-Exercises/chapter-15/ICE11.qmd"
          - text: "Week 13"
            href: "In-Class-Exercises/chapter-15/ICE12.qmd"
      - text: "Take Home Exercises"
        menu:
          - text: "Exercise 1"
            href: "Take-Home-Exercises/exe-01/THE1.qmd"
          - text: "Exercise 2"
            href: "Take-Home-Exercises/exe-02/THE2.qmd"
          - text: "Exercise 3"
            href: "Take-Home-Exercises/exe-03/THE3.qmd"
    right:
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

