project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "In Class Exercises"
        menu: 
          - text: "Week 2"
            href: "In-Class-Exercises/chapter-02/ICE2.qmd"
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

