project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Hands On Exercises"
        menu:
          - text: "Week 1"
            href: "Hands-On-Exercises/chapter-02/HOE1.qmd"
          - text: "Week 2"
            href: "Hands-On-Exercises/chapter-03/HOE2.qmd"
      - text: "In Class Exercises"
        menu: 
          - text: "Week 2"
            href: "In-Class-Exercises/chapter-02/ICE2.qmd"
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

