---
title: "In-Class Exercise 6: Spatial Weights and Applications"
format: html
author: "Jennifer Poernomo"
date: "13 February 2023"
date-modified: "`r Sys.Date()`"
execute: 
  message: false
  warning: false
editor: visual
---

# Import Packages

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

# Import Dataset

## Geospatial

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

## Aspatial

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

# Data Preprocessing

## Combining data frame with left join

::: callout-tip
## If you want to retain geometry, the left one must be the geospatial data
:::

```{r}
hunan_GDPPC <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
tm_shape(hunan_GDPPC)+
  tm_fill("GDPPC", 
          style = "quantile", 
          palette = "Blues",
          title = "GDPPC") +
  tm_layout(main.title = "Distribution of GDP per capita by district, Hunan Province",
            main.title.position = "center",
            main.title.size = 1,
            legend.outside = TRUE,
            legend.position = c("right", "bottom"),
            frame = TRUE) +
  tm_borders(alpha=0.5) +
  tm_compass(type="8star", size = 2) +
  tm_scale_bar() +
  tm_grid(alpha = 0.2)
```

# Identify Polygon Neighbors

```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb),
         .before = 1) # put newly-created field in first column
```

```{r}
wm_r <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry, queen = TRUE),
         wt = st_weights(nb),
         .before = 1) # put newly-created field in first column
```
